### ISSUE TITLE
Undefined error

### ISSUE THREAD

**Issue by rxgx** [diorahman/hapi-auth-stormpath#2]
When I use your example code from the README, the `error` function is called but the arguments are empty.

My example:

``` javascript
server.register({
  register: require('hapi-auth-stormpath'),
  options: {
    apiKey: {
      id: ENV.id,
      secret: ENV.secret
    },
    appHref: ENV.href
  }
}, function (err) {
  log.info('AUTH ERROR', err);
});
```

Outputs:
`{"message":"AUTH ERROR undefined"}`

**Comment by diorahman** [comment]
Thanks for this, hopefully 86068ab fixes this.
